### ISSUE TITLE
Hide unused GitHub Features

### ISSUE THREAD

**Issue by krishguptadev** [Kira272921/Kira272921#3]
![image](https://user-images.githubusercontent.com/91655303/145220625-201b1b4b-9185-4960-9cd6-44ca4b473c1e.png)
![image](https://user-images.githubusercontent.com/91655303/145220647-9bddc63c-4c1e-476b-b63c-38f74e5b0c27.png)

**Comment by Kira272921** [comment]
Thanks for letting me know 😄
